// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	meeting "cmd/app/entities/meeting"
	context "context"

	mock "github.com/stretchr/testify/mock"

	query "cmd/app/entities/meeting/query"

	uuid "github.com/gofrs/uuid/v5"
)

// MeetingsRepository is an autogenerated mock type for the MeetingsRepository type
type MeetingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MeetingsRepository) Create(ctx context.Context, _a1 *meeting.Meeting) (*meeting.Meeting, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *meeting.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *meeting.Meeting) (*meeting.Meeting, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *meeting.Meeting) *meeting.Meeting); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meeting.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *meeting.Meeting) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *MeetingsRepository) Delete(ctx context.Context, _a1 *meeting.Meeting) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *meeting.Meeting) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCriteria provides a mock function with given fields: ctx, criteria
func (_m *MeetingsRepository) FindByCriteria(ctx context.Context, criteria query.FindCriteria) ([]meeting.Meeting, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindByCriteria")
	}

	var r0 []meeting.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.FindCriteria) ([]meeting.Meeting, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.FindCriteria) []meeting.Meeting); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meeting.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.FindCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MeetingsRepository) FindByID(ctx context.Context, id uuid.UUID) (*meeting.Meeting, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *meeting.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*meeting.Meeting, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *meeting.Meeting); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meeting.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MeetingsRepository) Update(ctx context.Context, _a1 *meeting.Meeting) (*meeting.Meeting, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *meeting.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *meeting.Meeting) (*meeting.Meeting, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *meeting.Meeting) *meeting.Meeting); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meeting.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *meeting.Meeting) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMeetingsRepository creates a new instance of MeetingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeetingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeetingsRepository {
	mock := &MeetingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
